config/routes.rb
Rails.application.routes.draw do
  resources :clients do
    resources :indetifications
  end
  resources :clients do
    resources :money
  end
  get '/money/find', to: 'money#find', as: 'find_money'
  get '/money/find/client', to: 'money#findClient'
  get '/money/find/:num_money',to:'money#findMoney'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'index#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :indetifications
  has_many :money
end

app/models/indetification.rb
class Indetification < ApplicationRecord
  belongs_to :client
end

app/models/money.rb
class Money < ApplicationRecord
  belongs_to :client
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :address, :number_phones, :born_date, :email, :picture, :huella, :zipcode, :city, :state, :country, :type_cliente, :banned)
    end
end

app/controllers/indetifications_controller.rb
class IndetificationsController < ApplicationController
  before_action :set_indetifications
  before_action :set_indetification, only: [:show, :edit, :update, :destroy]

  # GET clients/1/indetifications
  def index
    @indetifications = @client.indetifications
  end

  # GET clients/1/indetifications/1
  def show
  end

  # GET clients/1/indetifications/new
  def new
    @indetification = @client.indetifications.build
  end

  # GET clients/1/indetifications/1/edit
  def edit
  end

  # POST clients/1/indetifications
  def create
    @indetification = @client.indetifications.build(indetification_params)

    if @indetification.save
      redirect_to([@indetification.client, @indetification], notice: 'Indetification was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT clients/1/indetifications/1
  def update
    if @indetification.update_attributes(indetification_params)
      redirect_to([@indetification.client, @indetification], notice: 'Indetification was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE clients/1/indetifications/1
  def destroy
    @indetification.destroy

    redirect_to client_indetifications_url(@client)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indetifications
      @client = Client.find(params[:client_id])
    end

    def set_indetification
      @indetification = @client.indetifications.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def indetification_params
      params.require(:indetification).permit(:id_number, :expiration_date, :id_type, :expedition_date, :expedition_country)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
    before_action :authenticate_user!
    def index
        @checks = Money.all
    end
end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
  before_action do |controller|
    if action_name != "find" && action_name != "findClient" && action_name != "findMoney"
      set_client()
    end
  end
  before_action :set_money, only: [:show, :edit, :update, :destroy]

  # GET clients/1/money
  def index
    @money = @client.money
  end

  # GET clients/1/money/1
  def show
  end

  # GET money/find/1
  def findMoney
    @money = Money.find(params[:num_money])
    redirect_to([@money.client, @money], notice: 'Money was successfully created.')
  end
  # GET  /money/find
  def find 
    if user_signed_in?
      @clients = Client.select("id,name").to_json
      @cli = @clients.gsub! "id","value"
      @cli = @clients.gsub! "name","label"
      if @cli.blank?
        @error = "Not Client created"    
      else

      end
    else
      "{}"
    end  
  end

  def findClient
    if user_signed_in?
      render status:200,  json: @clients = Client.select("id,name").to_json.gsub!(/\"/, '\'') 
    else
      "{}"
    end  
  end
  # GET clients/1/money/new
  def new
    @money = @client.money.build
  end

  # GET clients/1/money/1/edit
  def edit
  end

  # POST clients/1/money
  def create
    @money = @client.money.build(money_params)
    @money.user_id = current_user.id
    if @money.save
      redirect_to([@money.client, @money], notice: 'Money was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT clients/1/money/1
  def update
    if @money.update_attributes(money_params)
      redirect_to([@money.client, @money], notice: 'Money was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE clients/1/money/1
  def destroy
    @money.destroy

    redirect_to client_money_index_url(@client)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:client_id])
    end

    def set_money
      @money = @client.money.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def money_params
      params.require(:money).permit(:cash_number, :enterprise_name, :money, :rate, :money_date, :redeemed, :comment, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/indetifications_helper.rb
module IndetificationsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/money_helper.rb
module MoneyHelper
end

app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :number_phones %>
    <%= f.text_field :number_phones %>
  </div>

  <div class="field date">
    <%= f.label :born_date %>
    <%= f.date_select :born_date,start_year: 1900 %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.text_field :picture %>
  </div>

  <div class="field">
    <%= f.label :huella %>
    <%= f.text_field :huella %>
  </div>

  <div class="field">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :type_cliente %>
    <%= f.number_field :type_cliente %>
  </div>

  <div class="field">
    <%= f.label :banned %>
    <%= f.number_field :banned %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Number phones</th>
      <th>Born date</th>
      <th>Email</th>
      <th>Picture</th>
      <th>Huella</th>
      <th>Zipcode</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Type cliente</th>
      <th>Banned</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.address %></td>
        <td><%= client.number_phones %></td>
        <td><%= client.born_date %></td>
        <td><%= client.email %></td>
        <td><%= client.picture %></td>
        <td><%= client.huella %></td>
        <td><%= client.zipcode %></td>
        <td><%= client.city %></td>
        <td><%= client.state %></td>
        <td><%= client.country %></td>
        <td><%= client.type_cliente %></td>
        <td><%= client.banned %></td>
        <td><%= link_to 'Show', client %>
        <%= link_to 'Edit', edit_client_path(client) %>
        <%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Check', client_money_index_path(client) %>
        <%= link_to 'Indentification', client_indetifications_path(client) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Number phones:</strong>
  <%= @client.number_phones %>
</p>

<p>
  <strong>Born date:</strong>
  <%= @client.born_date %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @client.picture %>
</p>

<p>
  <strong>Huella:</strong>
  <%= @client.huella %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @client.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @client.country %>
</p>

<p>
  <strong>Type cliente:</strong>
  <%= @client.type_cliente %>
</p>

<p>
  <strong>Banned:</strong>
  <%= @client.banned %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/indetifications/_form.html.erb
<%= form_for([@indetification.client, @indetification]) do |f| %>
  <% if @indetification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@indetification.errors.count, "error") %> prohibited this indetification from being saved:</h2>

      <ul>
      <% @indetification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_number %><br />
    <%= f.text_field :id_number %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br />
    <%= f.date_select :expiration_date %>
  </div>
  <div class="field">
    <%= f.label :id_type %><br />
    <%= f.text_field :id_type %>
  </div>
  <div class="field">
    <%= f.label :expedition_date %><br />
    <%= f.date_select :expedition_date %>
  </div>
  <div class="field">
    <%= f.label :expedition_country %><br />
    <%= f.date_select :expedition_country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/indetifications/edit.html.erb
<h1>Editing indetification</h1>

<%= render 'form' %>

<%= link_to 'Show', [@indetification.client, @indetification] %> |
<%= link_to 'Back', client_indetifications_path(@indetification.client) %>

app/views/indetifications/index.html.erb
<h1>Listing indetifications</h1>

<table>
  <tr>
    <th>Id number</th>
    <th>Expiration date</th>
    <th>Id type</th>
    <th>Expedition date</th>
    <th>Expedition country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @indetifications.each do |indetification| %>
  <tr>
    <td><%= indetification.id_number %></td>
    <td><%= indetification.expiration_date %></td>
    <td><%= indetification.id_type %></td>
    <td><%= indetification.expedition_date %></td>
    <td><%= indetification.expedition_country %></td>
    <td><%= link_to 'Show', [indetification.client, indetification] %></td>
    <td><%= link_to 'Edit', edit_client_indetification_path(indetification.client, indetification) %></td>
    <td><%= link_to 'Destroy', [indetification.client, indetification], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Indetification', new_client_indetification_path(params[:client_id]) %>

app/views/indetifications/new.html.erb
<h1>New indetification</h1>

<%= render 'form' %>

<%= link_to 'Back', client_indetifications_path(@indetification.client) %>

app/views/indetifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id number:</b>
  <%= @indetification.id_number %>
</p>

<p>
  <b>Expiration date:</b>
  <%= @indetification.expiration_date %>
</p>

<p>
  <b>Id type:</b>
  <%= @indetification.id_type %>
</p>

<p>
  <b>Expedition date:</b>
  <%= @indetification.expedition_date %>
</p>

<p>
  <b>Expedition country:</b>
  <%= @indetification.expedition_country %>
</p>


<%= link_to 'Edit', edit_client_indetification_path(@indetification.client, @indetification) %> |
<%= link_to 'Back', client_indetifications_path(@indetification.client) %>

app/views/index/index.html.erb
<h2>Welcome to The Checking</h2>
<h3>this is software in production. it find upgrade the hand of the banck check</h3>
<h5>Total checks : <%= @checks.size %></h5>
    <ul>
        <li>
            <h6>Checks < 1000 : <%= @checks.select{ |s|  s.money < 1000 }.size %> </h6>
        </li>
        <li>
            <h6>Checks > 1000 and < 3000 : <%= @checks.select{ |s|  s.money >= 1000 and s.money < 3000 }.size %> </h6>
        </li>
        <li>
            <h6>Checks > 3000 : <span style="color:brown"><%= @checks.select{ |s|  s.money > 3000 }.size %></span></h6>
        </li>
    </ul>

app/views/layouts/_itemsheader.html.erb
<button class="accordion">Clientes</button>
<div class="panel">
  <ul>
    <li><%= link_to "view clients", clients_path %></li>
    <li><%= link_to "new clients", new_client_path %></li>
  </ul>
</div>

<button class="accordion">Money</button>
<div class="panel">
  <ul>
    <li><%= link_to "create money", find_money_path %></li>
    <li>Nr: <input type="text" id="find_money_menu" /><button id="button_find_money_menu" onclick="findMoney($('#find_money_menu').val())" >find</button></li>
  </ul>
</div>

<button class="accordion">Section 3</button>
<div class="panel">
  <ul>
    <li></li>
  </ul>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].onclick = function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheChecking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <% if user_signed_in? %>
        <%= render "layouts/itemsheader" %>
        <a><%= link_to "Logout", destroy_user_session_path, :method => :delete,:class => 'blue-text text-darken-2 ' %></a>
      <% else %>
        <a><%= link_to "Sign in",  new_user_session_path%></a>
      <% end %>
    </div>

    
  <body id="content-main">
  <div class="row">
      <div class="col s12">
        <div class="  notificaciones">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </div>
    </div>
    <div class="content-master container">
      <span id="button-menu" onclick="openNav()"><i class="material-icons">menu</i></span>
      <%= yield %>
    </div>

   



  </body>
  <div class="overlay" id="overlay">
  </div>
</html>

app/views/money/_form.html.erb
<%= form_for([@money.client, @money]) do |f| %>
  <% if @money.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@money.errors.count, "error") %> prohibited this money from being saved:</h2>

      <ul>
      <% @money.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cash_number %><br />
    <%= f.text_field :cash_number %>
  </div>
  <div class="field">
    <%= f.label :enterprise_name %><br />
    <%= f.text_field :enterprise_name %>
  </div>
  <div class="field">
    <%= f.label :money %><br />
    <%= f.text_field :money %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :money_date %><br />
    <%= f.date_select :money_date %>
  </div>
  <div class="field">
    <%= f.label :redeemed %><br />
    <%= f.check_box :redeemed %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/money/edit.html.erb
<h1>Editing money</h1>

<%= render 'form' %>

<%= link_to 'Show', [@money.client, @money] %> |
<%= link_to 'Back', client_money_index_path(@money.client) %>

app/views/money/find.html.erb
<h3><%= @error %></h3>

<% if !@cli.blank? %>
    <div class="row">
        <div class="col s12">
            <div class="row">
                <h3>write name of client to find</h3>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">textsms</i>
                    <input type="text" id="autocomplete-input" class="autocomplete">
                    <label for="autocomplete-input">Autocomplete</label>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('input.autocomplete').autocomplete({
            source: <%= @cli.html_safe   %>,
            minLength: 2,
            select: function( event, ui ) {
                window.location.href = "../clients/"+ui.item.value+"/money"
            },
            limit: 20, // The max amount of results that can be shown at once. Default: Infinity.
            onAutocomplete: function (val) {
                // Callback function when value is autcompleted.
            },
            minLength: 3, // The minimum length of the input for the autocomplete to start. Default: 1.
        });

    </script>
<% end %>

app/views/money/index.html.erb
<h2>Listing money of <%=@client.name%></h2>

<table>
  <tr>
    <th>Cash number</th>
    <th>Enterprise name</th>
    <th>Total Amount</th>
    <th>Rate</th>
    <th>Money date</th>
    <th>Redeemed</th>
    <th>Comment</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @money.each do |money| %>
  <tr>
    <td><%= money.cash_number %></td>
    <td><%= money.enterprise_name %></td>
    <td><%= money.money %></td>
    <td><%= money.rate %></td>
    <td><%= money.money_date %></td>
    <td><%= money.redeemed %></td>
    <td><%= money.comment %></td>
    <td><%= money.user_id %></td>
    <td><%= link_to 'Show', [money.client, money] %></td>
    <td><%= link_to 'Edit', edit_client_money_path(money.client, money) %></td>
    <td><%= link_to 'Destroy', [money.client, money], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Money', new_client_money_path(params[:client_id]) %>

app/views/money/new.html.erb
<h1>New money</h1>

<%= render 'form' %>

<%= link_to 'Back', client_money_index_path(@money.client) %>

app/views/money/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cash number:</b>
  <%= @money.cash_number %>
</p>

<p>
  <b>Enterprise name:</b>
  <%= @money.enterprise_name %>
</p>

<p>
  <b>Money:</b>
  <%= @money.money %>
</p>

<p>
  <b>Rate:</b>
  <%= @money.rate %>
</p>

<p>
  <b>Money date:</b>
  <%= @money.money_date %>
</p>

<p>
  <b>Redeemed:</b>
  <%= @money.redeemed %>
</p>

<p>
  <b>Comment:</b>
  <%= @money.comment %>
</p>

<p>
  <b>User:</b>
  <%= @money.user_id %>
</p>


<%= link_to 'Edit', edit_client_money_path(@money.client, @money) %> |
<%= link_to 'Back', client_money_index_path(@money.client) %>